// Code generated by protoc-gen-go.
// source: dc.proto
// DO NOT EDIT!

/*
Package dc is a generated protocol buffer package.

It is generated from these files:
	dc.proto

It has these top-level messages:
	Request
	Reply
	Node
	Edge
*/
package dc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Genes    []string `protobuf:"bytes,2,rep,name=genes" json:"genes,omitempty"`
	Ontology string   `protobuf:"bytes,1,opt,name=ontology" json:"ontology,omitempty"`
	Growth   bool     `protobuf:"varint,3,opt,name=growth" json:"growth,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetGenes() []string {
	if m != nil {
		return m.Genes
	}
	return nil
}

func (m *Request) GetOntology() string {
	if m != nil {
		return m.Ontology
	}
	return ""
}

func (m *Request) GetGrowth() bool {
	if m != nil {
		return m.Growth
	}
	return false
}

type Reply struct {
	Nodes []*Node `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
	Edges []*Edge `protobuf:"bytes,4,rep,name=edges" json:"edges,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Reply) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type Node struct {
	Id         string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Importance float64 `protobuf:"fixed64,2,opt,name=importance" json:"importance,omitempty"`
	Phenotype  float64 `protobuf:"fixed64,3,opt,name=phenotype" json:"phenotype,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetImportance() float64 {
	if m != nil {
		return m.Importance
	}
	return 0
}

func (m *Node) GetPhenotype() float64 {
	if m != nil {
		return m.Phenotype
	}
	return 0
}

type Edge struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Target string `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
}

func (m *Edge) Reset()                    { *m = Edge{} }
func (m *Edge) String() string            { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()               {}
func (*Edge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Edge) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Edge) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Reply)(nil), "Reply")
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*Edge)(nil), "Edge")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DeepCell service

type DeepCellClient interface {
	Run(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type deepCellClient struct {
	cc *grpc.ClientConn
}

func NewDeepCellClient(cc *grpc.ClientConn) DeepCellClient {
	return &deepCellClient{cc}
}

func (c *deepCellClient) Run(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/DeepCell/Run", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DeepCell service

type DeepCellServer interface {
	Run(context.Context, *Request) (*Reply, error)
}

func RegisterDeepCellServer(s *grpc.Server, srv DeepCellServer) {
	s.RegisterService(&_DeepCell_serviceDesc, srv)
}

func _DeepCell_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeepCellServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DeepCell/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeepCellServer).Run(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeepCell_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DeepCell",
	HandlerType: (*DeepCellServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _DeepCell_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dc.proto",
}

func init() { proto.RegisterFile("dc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x4d, 0xbf, 0x6c, 0x47, 0xf0, 0x10, 0x44, 0xe2, 0x2a, 0x52, 0x0a, 0x42, 0x4f, 0x3d,
	0xac, 0xe0, 0x5d, 0xd4, 0xab, 0x87, 0xd1, 0x3f, 0xb0, 0x36, 0x43, 0xb6, 0x50, 0x33, 0xb1, 0x4d,
	0x91, 0xfe, 0x7b, 0x69, 0x1b, 0xd4, 0xe3, 0xf3, 0x4c, 0x98, 0x79, 0xf3, 0x42, 0xae, 0xdb, 0xc6,
	0x0d, 0xec, 0xb9, 0x7a, 0x83, 0x53, 0xa4, 0xaf, 0x89, 0x46, 0x2f, 0x2f, 0x20, 0x35, 0x64, 0x69,
	0x54, 0x51, 0x19, 0xd7, 0x05, 0x6e, 0x20, 0x77, 0x90, 0xb3, 0xf5, 0xdc, 0xb3, 0x99, 0x95, 0x28,
	0x45, 0x5d, 0xe0, 0x2f, 0xcb, 0x4b, 0xc8, 0xcc, 0xc0, 0xdf, 0xfe, 0xa8, 0xe2, 0x52, 0xd4, 0x39,
	0x06, 0xaa, 0x1e, 0x21, 0x45, 0x72, 0xfd, 0x2c, 0xaf, 0x21, 0xb5, 0xac, 0x69, 0x54, 0x71, 0x19,
	0xd7, 0x67, 0xfb, 0xb4, 0x79, 0x65, 0x4d, 0xb8, 0xb9, 0x65, 0x48, 0xda, 0xd0, 0xa8, 0x92, 0x30,
	0x7c, 0xd1, 0x86, 0x70, 0x73, 0xd5, 0x3b, 0x24, 0xcb, 0x5b, 0x79, 0x0e, 0x51, 0xa7, 0xc3, 0xe1,
	0xa8, 0xd3, 0xf2, 0x16, 0xa0, 0xfb, 0x74, 0x3c, 0xf8, 0x83, 0x6d, 0x49, 0x45, 0xa5, 0xa8, 0x05,
	0xfe, 0x33, 0xf2, 0x06, 0x0a, 0x77, 0x24, 0xcb, 0x7e, 0x76, 0xb4, 0xa6, 0x12, 0xf8, 0x27, 0xaa,
	0x07, 0x48, 0x96, 0x23, 0x4b, 0xf0, 0x91, 0xa7, 0xa1, 0xa5, 0xb0, 0x39, 0xd0, 0xe2, 0xfd, 0x61,
	0x30, 0xe4, 0xd7, 0xcd, 0x05, 0x06, 0xda, 0xdf, 0x41, 0xfe, 0x4c, 0xe4, 0x9e, 0xa8, 0xef, 0xe5,
	0x15, 0xc4, 0x38, 0x59, 0x99, 0x37, 0xa1, 0xb7, 0x5d, 0xd6, 0xac, 0x9f, 0xad, 0x4e, 0x3e, 0xb2,
	0xb5, 0xd3, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0xa7, 0x30, 0x12, 0x5f, 0x01, 0x00,
	0x00,
}
