version: '2'
services:
  elasticsearch:
    build: ./elastic
    restart: always
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ./elastic/backend_deep-cell/_data:/usr/share/elasticsearch/data

  search-proxy:
    build: ./search-proxy
    restart: always
    ports:
      - "3000:3000"

  predictor:
    build: ./predictor
    restart: always
    ports:
      - "8888:8888"

  go-util:
    build: ./gene-ontology
    restart: always
    ports:
      - "5000:5000"

  static:
    build: ./webserver
    restart: always
    ports:
      - "80:80"

volumes:
  deep-cell:
    driver: local
