# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dc_pb2 as dc__pb2


class DeepCellStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Run = channel.unary_unary(
        '/DeepCell/Run',
        request_serializer=dc__pb2.Request.SerializeToString,
        response_deserializer=dc__pb2.Reply.FromString,
        )


class DeepCellServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeepCellServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Run': grpc.unary_unary_rpc_method_handler(
          servicer.Run,
          request_deserializer=dc__pb2.Request.FromString,
          response_serializer=dc__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DeepCell', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
